-- Migration: [DESCRIPTION OF CHANGES]
-- Date: [YYYY-MM-DD]
-- Description: [Detailed explanation of what this migration does and why]
-- 
-- ⚠️ DEVELOPER ACTION REQUIRED:
-- This migration must be executed manually in phpMyAdmin due to hosting restrictions
-- 
-- 📋 EXECUTION STEPS:
-- 1. Open phpMyAdmin and navigate to democrm_democrm database
-- 2. Copy and paste the SQL statements below into the SQL tab
-- 3. Execute the statements one by one or all at once
-- 4. Verify the changes were applied successfully
-- 
-- 🔔 CRITICAL: AFTER MIGRATION EXECUTION
-- You MUST update the structure file! Run this command after executing the migration:
-- 
--    php scripts/update_structure_reminder.php sql/migrations/[THIS_FILE_NAME].sql
-- 
-- This will remind you to export the updated database structure from phpMyAdmin
-- and replace /sql/democrm_democrm_structure.sql with the new version.
-- 
-- 💡 WHY STRUCTURE UPDATE IS REQUIRED:
-- - Fresh installations use the structure file
-- - Other developers need the updated schema
-- - Deployment processes rely on this file
-- - It serves as the authoritative database reference
-- 
-- ==================================================================================
-- Your migration SQL statements go here:
-- Example:
-- ALTER TABLE table_name
-- ADD COLUMN new_field_name INT DEFAULT NULL COMMENT 'Field description' AFTER existing_field;
-- ==================================================================================
-- 
-- 🎯 POST-MIGRATION CHECKLIST:
-- □ Migration executed successfully in phpMyAdmin
-- □ New columns/tables verified in database
-- □ Application tested with new schema
-- □ Structure file updated (run reminder script above)
-- □ Changes committed to version control
-- 
-- ==================================================================================